---
title: "run"
author: "DrBriody"
date: "12/01/2023"
---

```{r}
source_rmd = function(file, ...) {
  tmp_file = tempfile(fileext=".R")
  on.exit(unlink(tmp_file), add = TRUE)
  knitr::purl(file, output=tmp_file)
  source(file = tmp_file, ...)
}

# This is a function (based on the below link) that grabs a file we give it in the next code chunk below, temporarily makes it an R file rather than an Rmarkdown file using purl and then sources this file for us (i.e., runs everything).

# I apply the source_rmd function to source an R markdown document of my choice.

# https://stackoverflow.com/questions/70535350/run-rmarkdown-rmd-from-inside-another-rmd-without-creating-html-output
# Also saved here: r - Run RMarkdown (.rmd) from inside another .rmd without creating HTML output - Stack Overflow.pdf

```

```{r}

# A warning that the below will take a bit of time to calculate for all 3 countries (maybe 20 minutes in total to finish the report), so be ready to wait a little.

# Basically, what I have is 1 Rmarkdown document with appropriate CEA code, but 3 countries I want to apply separately this code to, because costs (and willingness to pay thresholds) are different in each of these 3 countries.

# To do this, I feed in the cost data from each country for parameters that differ across countries:


# Ireland:


# 1. Cost of treatment in this country
c_PFS_Folfox <- 307.81 
c_PFS_Bevacizumab <- 2580.38  
c_OS_Folfiri <- 326.02  
administration_cost <- 365.00 

# 2. Cost of treating the AE conditional on it occurring
c_AE1 <- 2835.89
c_AE2 <- 1458.80
c_AE3 <- 409.03 

# 3. Willingness to pay threshold
n_wtp = 45000


# I apply the source_rmd function to source the core R markdown CEA document when costs are specific to the country of choice.

source_rmd("Markov_3state.rmd")


# For building the Table in the paper, I create country specific versions of the parameters to be included in the Table, as informed by the parameter names in the table:


Ireland_c_PFS_Folfox <- c_PFS_Folfox 
Ireland_c_PFS_Bevacizumab <- c_PFS_Bevacizumab  
Ireland_c_OS_Folfiri <- c_OS_Folfiri  
Ireland_administration_cost <- administration_cost 
n_wtp <-
tc_d_Exp
Ireland_tc_d_SoC

Incremental_Cost<- noquote(table_cea$"Incremental Costs"[2])
Incremental_Effect<- round(df_cea$Inc_Effect[2], digits=3)
ICER<- noquote(table_cea$"ICER"[2])

# PSA Version of the above:

PSA_Incremental_Cost<- noquote(table_cea_PA$"Incremental Costs"[2])
PSA_Incremental_Effect<- round(df_cea_PA$Inc_Effect[2], digits=3)
PSA_ICER<- noquote(table_cea_PA$"ICER"[2])


# I remove everything [rm( )] everything except the specific objects I include in the wrute-up analysis, to create each parameter from scratch, this ensures that there arent situations where a variable is created once when the rmarkdown file is first run, and then iterated on and increased or changed in some way from this starting point in the second and third run.


keep(plot1, plot2, plot3, sure = TRUE)
# I need to think about how this fits with the rm(list = ls()) currently in my Rmarkdown file.

# I use the keep function from the gdata package as described here: https://stackoverflow.com/questions/6190051/how-can-i-remove-all-objects-but-one-from-the-workspace-in-r/7205040#7205040


# Then, I repeat all of this exactly for the other countries I am studying:








# Now I can look at the ICERs and graphs, etc., from each of these countries and apply them in the appropriate places in this R Markdown document for the academic report.
```

```{r}
kk <- data.frame(c_PFS_Folfox, c_PFS_Bevacizumab, c_OS_Folfiri, administration_cost, c_AE1, c_AE2, c_AE3, n_wtp)
                 

# kk <- paste("Ireland", kk, sep="_")

# kk

#colnames(kk) <- paste("Ireland", kk, sep="_")

colnames(kk) <- paste("Ireland", colnames(kk), sep="_")

kk

```

```{r echo=TRUE}
plot9
```

```{plot(cars)}
```

```{r}
(`r knitr::fig_chunk('cars-plot', 'png')`)
```

```{r}
plot(mtcars$mpg~mtcars$disp)
```

```{r}
png(paste("myplot_", country_name[i], ".png", sep = ""))
plot9
dev.off()
```

```{# also}

# I can add the following to the above: 

# + ggtitle("Expected Value of Perfect Information")
#txtsize - base text size
```

```{r}

# Bits for the paper:




# Appendix:


# Compare the fit of the different distributions to the survival data numerically based on the AIC

v_AIC_TTP
(v_AIC_TTP <- c(
  exp      = l_TTP_SoC_exp$AIC,
  gamma    = l_TTP_SoC_gamma$AIC,
  gompertz = l_TTP_SoC_gompertz$AIC,
  llogis   = l_TTP_SoC_llogis$AIC,
  lnorm    = l_TTP_SoC_lnorm$AIC,
  weibull  = l_TTP_SoC_weibull$AIC
))


v_AIC_TTD
(v_AIC_TTD <- c(
  exp      = l_TTP_SoC_exp$AIC,
  gamma    = l_TTP_SoC_gamma$AIC,
  gompertz = l_TTP_SoC_gompertz$AIC,
  llogis   = l_TTP_SoC_llogis$AIC,
  lnorm    = l_TTP_SoC_lnorm$AIC,
  weibull  = l_TTP_SoC_weibull$AIC
))





# I don't save these values using "keep" as they'll be leftover from running the code, and should always come out the same as they are from the ANGIOPREDICT data on peoples survival and not dependent on the country we are studying, so the last country studied should have them saved on the final run of the model.

# Similarly for life_years_days_gained life_years_soc, life_years_exp





```

There are some things that I would like to appear in the code chunks, but not in the knitted document. To do this I can go to:

<https://stackoverflow.com/questions/47710427/how-to-show-code-but-hide-output-in-rmarkdown>

and

<https://stackoverflow.com/questions/48286722/rmarkdown-how-to-show-partial-output-from-chunk?rq=1>

Although I can probably just use:

knitr::opts_chunk\$set(echo = TRUE, warning = FALSE, message = FALSE, eval = T)

But set echo = false

Or even better, click the gear on each code chunk and decide if I would like that code chunk to show things or not.

## References:
