<<<<<<< HEAD
---
title: "Untitled"
output: html_document
date: "2023-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Render

```{r pressure, echo=TRUE}
rmarkdown::render("test1.Rmd")
```

```{r}

# For building the Table in the paper, I create country specific versions of the parameters to be included in the Table, as informed by the parameter names in the table:

vars_2_keep <- data.frame(c_PFS_Folfox, c_PFS_Bevacizumab, c_OS_Folfiri, administration_cost, c_AE1, c_AE2, c_AE3, Minimum_c_PFS_Folfox, Maximum_c_PFS_Folfox, Minimum_c_OS_Folfiri, Maximum_c_OS_Folfiri, Minimum_c_PFS_Bevacizumab, Maximum_c_PFS_Bevacizumab, Minimum_administration_cost, Maximum_administration_cost, Minimum_c_AE1, Maximum_c_AE1, Minimum_c_AE2, Maximum_c_AE2, Minimum_c_AE3, Maximum_c_AE3, n_wtp, Incremental_Cost, Incremental_Effect, ICER, tc_d_Exp, tc_d_SoC)

# Then I name these parameters after the country I am studying:

list2env(setNames(vars_2_keep, paste0(country_name[1], "_", sep = "", names(vars_2_keep))), .GlobalEnv)

# As informed by:

# https://stackoverflow.com/questions/75115247/how-can-i-copy-and-rename-a-bunch-of-variables-at-once/75115552?noredirect=1#comment132555463_75115552

# Then I save these 

x <- 10

vars_2_keep <- data.frame(x)

country_name <- "Ireland"

dataframename <- country_name

save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))

load(file='my_data_Ireland.rda')




save(vars_2_keep, file='my_data_.rda')

  assign(paste("New data",i,sep=""), data.frame(vars_2_keep))) %>% mutate(colthree=(colone+coltwo)*i) %>% select(colthree)


rm()

load(file='dataframename.rda')





mv(from = "vars_2_keep", to = country_name[1])


save(country_name, file=paste("my_data_", country_name[1], ".rda", sep = ""))


load(file='my_data_Ireland.rda')





assign("new.name",old.name)

      
paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep

# I create a country specific Rdata file to store all these country specific values:


paste0("x_", country_name[1], "_", sep = "") <- data.frame(x=rnorm(100))




paste("perf.a", country_name[1], sep="") <- data.frame(x)

country_name <- "Ireland"

save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))



keep(country_name[1], sure = TRUE)


paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep



keep(vars_2_keep$x, sure = TRUE)











```

```{r}
# I have a parameter called country_name that I change sometimes when I run my code, I would like my RDA file to reflect that name change once saved and loaded back into the environment.

# Currently what happens is this:

# Name the country:

country_name <- "Ireland"

# Create a simple data frame:

x <- 10

y <- 100

z <- 1000


vars_2_keep <- data.frame(x)

vars_2_keep

#save to rda file
save(x, y, z, file=paste("my_data_", country_name[1], ".rda", sep = ""))


#country_name[1] <- vars_2_keep; save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))

rm(list=ls())

load(file='my_data_Ireland.rda')

country_name <- "Ireland"

vars_2_keep <- data.frame(x, y, z)
      
paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep









# It contains x=10

# x
# 1 10

# I save it, renaming the data frame with the country name so that when I do this with a different country I will have country specific vectors:

assign(paste0("my_data_", country_name[1]), vars_2_keep)





save(my_data_Ireland, file=paste("my_data_", country_name[1], ".rda", sep = ""))

# I delete everything, and load it back in:


# Unfortunately, in the environment instead of my data frame being called "my_data_Ireland", it is still called vars_2_keep.

# How can I update the name of this data frame to my_data_country_name[1]

# Thank you
```











```{r}

# I apply the source_rmd function to source the core R markdown CEA document when costs are specific to the country of choice.

source_rmd("Markov_3state.rmd")

# For building the Table in the paper, and for referring to parameter values in the paper, I saved the parameters I created in the RMarkdown file I called in an RDA file named after the country I am studying:

# now I load that RDA datafile for each country:

load(file='my_data_Ireland.rda')

# I create a data frame of all the parameters in that file:

vars_2_keep <- data.frame(c_PFS_Folfox, c_PFS_Bevacizumab, c_OS_Folfiri, administration_cost, c_AE1, c_AE2, c_AE3, Minimum_c_PFS_Folfox, Maximum_c_PFS_Folfox, Minimum_c_OS_Folfiri, Maximum_c_OS_Folfiri, Minimum_c_PFS_Bevacizumab, Maximum_c_PFS_Bevacizumab, Minimum_administration_cost, Maximum_administration_cost, Minimum_c_AE1, Maximum_c_AE1, Minimum_c_AE2, Maximum_c_AE2, Minimum_c_AE3, Maximum_c_AE3, n_wtp, Incremental_Cost, Incremental_Effect, ICER, tc_d_Exp, tc_d_SoC)

# And I name them after the country in question:

paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep
```




























=======
---
title: "Untitled"
output: html_document
date: "2023-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Render

```{r pressure, echo=TRUE}
rmarkdown::render("test1.Rmd")
```

```{r}

# For building the Table in the paper, I create country specific versions of the parameters to be included in the Table, as informed by the parameter names in the table:

vars_2_keep <- data.frame(c_PFS_Folfox, c_PFS_Bevacizumab, c_OS_Folfiri, administration_cost, c_AE1, c_AE2, c_AE3, Minimum_c_PFS_Folfox, Maximum_c_PFS_Folfox, Minimum_c_OS_Folfiri, Maximum_c_OS_Folfiri, Minimum_c_PFS_Bevacizumab, Maximum_c_PFS_Bevacizumab, Minimum_administration_cost, Maximum_administration_cost, Minimum_c_AE1, Maximum_c_AE1, Minimum_c_AE2, Maximum_c_AE2, Minimum_c_AE3, Maximum_c_AE3, n_wtp, Incremental_Cost, Incremental_Effect, ICER, tc_d_Exp, tc_d_SoC)

# Then I name these parameters after the country I am studying:

list2env(setNames(vars_2_keep, paste0(country_name[1], "_", sep = "", names(vars_2_keep))), .GlobalEnv)

# As informed by:

# https://stackoverflow.com/questions/75115247/how-can-i-copy-and-rename-a-bunch-of-variables-at-once/75115552?noredirect=1#comment132555463_75115552

# Then I save these 

x <- 10

vars_2_keep <- data.frame(x)

country_name <- "Ireland"

dataframename <- country_name

save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))

load(file='my_data_Ireland.rda')




save(vars_2_keep, file='my_data_.rda')

  assign(paste("New data",i,sep=""), data.frame(vars_2_keep))) %>% mutate(colthree=(colone+coltwo)*i) %>% select(colthree)


rm()

load(file='dataframename.rda')





mv(from = "vars_2_keep", to = country_name[1])


save(country_name, file=paste("my_data_", country_name[1], ".rda", sep = ""))


load(file='my_data_Ireland.rda')





assign("new.name",old.name)

      
paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep

# I create a country specific Rdata file to store all these country specific values:


paste0("x_", country_name[1], "_", sep = "") <- data.frame(x=rnorm(100))




paste("perf.a", country_name[1], sep="") <- data.frame(x)

country_name <- "Ireland"

save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))



keep(country_name[1], sure = TRUE)


paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep



keep(vars_2_keep$x, sure = TRUE)











```

```{r}
# I have a parameter called country_name that I change sometimes when I run my code, I would like my RDA file to reflect that name change once saved and loaded back into the environment.

# Currently what happens is this:

# Name the country:

country_name <- "Ireland"

# Create a simple data frame:

x <- 10

y <- 100

z <- 1000


vars_2_keep <- data.frame(x)

vars_2_keep

#save to rda file
save(x, y, z, file=paste("my_data_", country_name[1], ".rda", sep = ""))


#country_name[1] <- vars_2_keep; save(vars_2_keep, file=paste("my_data_", country_name[1], ".rda", sep = ""))

rm(list=ls())

load(file='my_data_Ireland.rda')

country_name <- "Ireland"

vars_2_keep <- data.frame(x, y, z)
      
paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep









# It contains x=10

# x
# 1 10

# I save it, renaming the data frame with the country name so that when I do this with a different country I will have country specific vectors:

assign(paste0("my_data_", country_name[1]), vars_2_keep)





save(my_data_Ireland, file=paste("my_data_", country_name[1], ".rda", sep = ""))

# I delete everything, and load it back in:


# Unfortunately, in the environment instead of my data frame being called "my_data_Ireland", it is still called vars_2_keep.

# How can I update the name of this data frame to my_data_country_name[1]

# Thank you
```











```{r}

# I apply the source_rmd function to source the core R markdown CEA document when costs are specific to the country of choice.

source_rmd("Markov_3state.rmd")

# For building the Table in the paper, and for referring to parameter values in the paper, I saved the parameters I created in the RMarkdown file I called in an RDA file named after the country I am studying:

# now I load that RDA datafile for each country:

load(file='my_data_Ireland.rda')

# I create a data frame of all the parameters in that file:

vars_2_keep <- data.frame(c_PFS_Folfox, c_PFS_Bevacizumab, c_OS_Folfiri, administration_cost, c_AE1, c_AE2, c_AE3, Minimum_c_PFS_Folfox, Maximum_c_PFS_Folfox, Minimum_c_OS_Folfiri, Maximum_c_OS_Folfiri, Minimum_c_PFS_Bevacizumab, Maximum_c_PFS_Bevacizumab, Minimum_administration_cost, Maximum_administration_cost, Minimum_c_AE1, Maximum_c_AE1, Minimum_c_AE2, Maximum_c_AE2, Minimum_c_AE3, Maximum_c_AE3, n_wtp, Incremental_Cost, Incremental_Effect, ICER, tc_d_Exp, tc_d_SoC)

# And I name them after the country in question:

paste(country_name, colnames(vars_2_keep), sep="_") %=% vars_2_keep
```




























>>>>>>> f691f520d56b229ae5e891d942f6f964d9c7d025
